import type { TestCase } from "../../src/testHarness";
import type { solve } from "./solution";

export const cases: TestCase<Parameters<typeof solve>, ReturnType<typeof solve>>[] = [
  { name: "classic example one", input: ["abcabcbb"], expected: 3 },
  { name: "classic example two", input: ["bbbbb"], expected: 1 },
  { name: "classic example three", input: ["pwwkew"], expected: 3 },
  { name: "empty string", input: [""], expected: 0 },
  { name: "single character", input: ["a"], expected: 1 },
  { name: "single space", input: [" "], expected: 1 },
  { name: "single digit", input: ["7"], expected: 1 },
  { name: "single symbol", input: ["!"], expected: 1 },
  { name: "two identical characters", input: ["aa"], expected: 1 },
  { name: "two distinct characters", input: ["ab"], expected: 2 },
  { name: "all identical characters long", input: ["aaaaaaaaaaaaaaaa"], expected: 1 },
  { name: "all unique lowercase letters", input: ["abcdefghijklmnopqrstuvwxyz"], expected: 26 },
  { name: "all unique uppercase letters", input: ["ABCDEFGHIJKLMNOPQRSTUVWXYZ"], expected: 26 },
  { name: "classic tricky case dvdf", input: ["dvdf"], expected: 3 },
  { name: "classic tricky case abba", input: ["abba"], expected: 2 },
  { name: "classic tricky case tmmzuxt", input: ["tmmzuxt"], expected: 5 },
  { name: "repeat at very end", input: ["abcdefgha"], expected: 8 },
  { name: "repeat right after start", input: ["aab"], expected: 2 },
  { name: "longest window in the middle", input: ["xxabcdefxx"], expected: 7 },
  { name: "longest window at the end", input: ["aaaaabcdefg"], expected: 7 },
  { name: "longest window at the start", input: ["abcdefgaaaa"], expected: 7 },
  { name: "alternating two characters", input: ["ababababab"], expected: 2 },
  { name: "alternating three characters", input: ["abcabcabcabc"], expected: 3 },
  { name: "case sensitivity simple", input: ["aA"], expected: 2 },
  { name: "case sensitivity repeated", input: ["aAaAaA"], expected: 2 },
  { name: "digits only unique", input: ["1234567890"], expected: 10 },
  { name: "digits only repeating", input: ["1122334455"], expected: 2 },
  { name: "symbols only unique", input: ["!@#$%^&*()"], expected: 10 },
  { name: "symbols only repeating", input: ["!!@@##$$"], expected: 2 },
  { name: "spaces between unique words", input: ["a b c d e"], expected: 3 },
  { name: "spaces only", input: ["     "], expected: 1 },
  { name: "mixed letters digits symbols unique", input: ["a1!b2@c3#"], expected: 9 },
  { name: "mixed letters digits symbols repeating", input: ["a1!a1!a1!"], expected: 3 },
  { name: "leading repeat then long unique run", input: ["aaabcdefghijklmno"], expected: 15 },
  { name: "trailing repeat after long unique run", input: ["abcdefghijklmnoaaa"], expected: 15 },
  { name: "single repeat in the middle of unique run", input: ["abcdefgadefghij"], expected: 8 },
  { name: "palindrome-like string", input: ["abcdcba"], expected: 4 },
  { name: "palindrome with inner repeat", input: ["abccba"], expected: 3 },
  { name: "two-letter alphabet long run", input: ["abababababababababab"], expected: 2 },
  { name: "three-letter alphabet long run", input: ["aabbccaabbccaabbcc"], expected: 2 },
  { name: "window resets multiple times", input: ["abcabcdabcde"], expected: 5 },
  { name: "gradually growing unique prefix then repeat", input: ["abcdeabcde"], expected: 5 },
  { name: "single character repeated with one break", input: ["aaaXaaaa"], expected: 2 },
  { name: "sentence with punctuation", input: ["the quick brown fox!"], expected: 11 },
  { name: "sentence with repeated words", input: ["the cat sat on the mat"], expected: 6 },
  { name: "camelCase identifier", input: ["myVariableNameHere"], expected: 7 },
  { name: "snake_case identifier", input: ["my_variable_name_here"], expected: 8 },
  { name: "kebab-case identifier", input: ["my-variable-name-here"], expected: 8 },
  { name: "numeric sequence with repeat", input: ["0123456701234"], expected: 8 },
  { name: "long random mixed string", input: ["wobmxjssxrekz"], expected: 7 },
  { name: "all same digit long", input: ["9999999999999999999999999999"], expected: 1 },
  { name: "unique run then full reset", input: ["abcdefghabcdefgh"], expected: 8 },
  { name: "two long unique runs separated by repeat", input: ["abcdefgghijklmn"], expected: 8 },
  { name: "single unique char surrounded by same repeats", input: ["bab"], expected: 2 },
  { name: "three same characters", input: ["ccc"], expected: 1 },
  { name: "four alternating characters", input: ["abab"], expected: 2 },
  { name: "unicode-free extended ascii symbols", input: ["~`_-+=|\\{}[];:'\",.<>/?"], expected: 22 },
  { name: "tab and newline characters", input: ["a\tb\nc\td\ne"], expected: 5 },
  { name: "tab and newline with repeat", input: ["a\tb\na\tb"], expected: 4 },
  {
    name: "long string with one big unique block",
    input: ["zzzzzabcdefghijklmnopqrstuvwxyzzzzzz"],
    expected: 26,
  },
  {
    name: "string length fifty no repeats",
    input: ["!\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQR"],
    expected: 50,
  },
  {
    name: "string length fifty all repeats of two chars",
    input: ["xyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxyxy"],
    expected: 2,
  },
  {
    name: "string where answer is exactly one",
    input: ["zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz"],
    expected: 1,
  },
  { name: "repeating triplet pattern", input: ["xyzxyzxyzxyz"], expected: 3 },
  { name: "increasing then decreasing unique run", input: ["abcdefedcba"], expected: 6 },
  { name: "mixed case word boundary", input: ["aAbBcCdDaA"], expected: 8 },
  { name: "number then letters then repeat number", input: ["123abc123"], expected: 6 },
  { name: "letters then number then repeat letters", input: ["abc123abc"], expected: 6 },
  { name: "three distinct then repeat first", input: ["xyzx"], expected: 3 },
  { name: "three distinct then repeat middle", input: ["xyzy"], expected: 3 },
  { name: "three distinct then repeat last", input: ["xyzz"], expected: 3 },
  {
    name: "long alphabet cycle three times",
    input: ["abcdefghijabcdefghijabcdefghij"],
    expected: 10,
  },
  { name: "single space surrounded by letters", input: ["a b"], expected: 3 },
  { name: "consecutive spaces breaking unique run", input: ["abc   def"], expected: 4 },
  {
    name: "long unique string with trailing single repeat",
    input: ["abcdefghijklmnopqrstuvwxyza"],
    expected: 26,
  },
];
