import type { TestCase } from "../../src/testHarness";
import type { solve } from "./solution";

export const cases: TestCase<Parameters<typeof solve>, ReturnType<typeof solve>>[] = [
  { name: "single pair", input: ["()"], expected: true },
  { name: "multiple pair types", input: ["()[]{}"], expected: true },
  { name: "mismatched types", input: ["(]"], expected: false },
  { name: "nested", input: ["{[]}"], expected: true },
  { name: "wrong close order", input: ["(]"], expected: false },
  { name: "closes before opens", input: ["([)]"], expected: false },
  { name: "unclosed opener", input: ["((("], expected: false },
  { name: "unmatched closer", input: [")"], expected: false },
  { name: "empty string", input: [""], expected: true },
  { name: "deeply nested same type", input: ["((((()))))"], expected: true },
  { name: "deeply nested mixed types", input: ["({[({[]})]})"], expected: true },
  { name: "long valid sequence", input: ["()()()()()()()()()()"], expected: true },
  { name: "long invalid sequence trailing opener", input: ["()()()()()()()()()("], expected: false },
  { name: "all openers", input: ["((((((((("], expected: false },
  { name: "all closers", input: [")))))))))"], expected: false },
  { name: "single opener", input: ["("], expected: false },
  { name: "single closer", input: [")"], expected: false },
  { name: "adjacent mismatched pairs", input: ["()(]"], expected: false },
  { name: "reversed nesting", input: ["]})({["], expected: false },
  { name: "extra closer at end", input: ["()]"], expected: false },
  { name: "extra opener at start", input: ["[()"], expected: false },
  { name: "balanced but wrong nesting order", input: ["([)]"], expected: false },
  { name: "balanced with correct nesting order", input: ["([])"], expected: true },
  { name: "curly braces only nested", input: ["{{{}}}"], expected: true },
  { name: "square brackets only nested", input: ["[[[]]]"], expected: true },
  { name: "round brackets only sequential", input: ["()()"], expected: true },
  { name: "nested group then sequential pairs", input: ["(([{}]))[]{}"], expected: true },
  { name: "trailing unmatched opener after valid sequence", input: ["()[]{}["], expected: false },
  { name: "mixed sequential valid", input: ["()[]{}()"], expected: true },
  { name: "mixed sequential invalid", input: ["()[]{}("], expected: false },
  { name: "long alternating valid", input: ["(){}[](){}[](){}[]"], expected: true },
  { name: "long alternating invalid", input: ["(){}[](){}[](){}["], expected: false },
  { name: "nested then sequential", input: ["([{}])()"], expected: true },
  { name: "sequential then nested", input: ["()([{}])"], expected: true },
  { name: "unbalanced extra opener mid string", input: ["(()"], expected: false },
  { name: "unbalanced extra closer mid string", input: ["())"], expected: false },
  { name: "single character each type valid pairs", input: ["()"], expected: true },
  { name: "type mismatch simple curly round", input: ["{)"], expected: false },
  { name: "type mismatch simple square curly", input: ["[}"], expected: false },
  { name: "type mismatch simple round square", input: ["(]"], expected: false },
  { name: "double nested nested with mismatch", input: ["{[(])}"], expected: false },
  { name: "triple nested valid", input: ["{[()]}"], expected: true },
  { name: "long valid nested nested", input: ["((([{}])))"], expected: true },
  { name: "closer before any opener", input: [")("], expected: false },
  { name: "closer before any opener curly", input: ["}{"], expected: false },
  { name: "closer before any opener square", input: ["]["], expected: false },
  { name: "large valid random mix", input: ["([]){[()]}[{()}]"], expected: true },
  { name: "large invalid random mix", input: ["([]){[(])}[{()}]"], expected: false },
  { name: "single type long valid", input: ["()()()()()()()()()()()()()()()()()()()()"], expected: true },
  {
    name: "single type long invalid missing one closer",
    input: ["()()()()()()()()()()()()()()()()()()()("],
    expected: false,
  },
  { name: "invalid crossing brackets", input: ["{[}]"], expected: false },
  { name: "valid palindrome-like structure", input: ["([{}])"], expected: true },
  { name: "odd length always invalid", input: ["[[("], expected: false },
  { name: "odd length always invalid two", input: ["{[()]"], expected: false },
  { name: "repeated valid unit", input: ["{}{}{}{}{}"], expected: true },
  { name: "repeated invalid unit missing closer", input: ["{}{}{}{}{"], expected: false },
  { name: "nested nested nested valid nine deep", input: ["((({{{[[[]]]}}})))"], expected: true },
  { name: "nested nested nested invalid mismatch deep", input: ["((({{{[[[}]]}}])))"], expected: false },
  { name: "nested with trailing valid pair", input: ["[{}]()"], expected: true },
  // Non-bracket characters ('(){}[]' plus anything else) are treated as
  // no-ops: they're skipped entirely, and validity depends only on how the
  // bracket characters nest and match.
  { name: "letters around valid brackets", input: ["a(b)c"], expected: true },
  { name: "letters around invalid brackets", input: ["a(bc"], expected: false },
  { name: "digits around valid brackets", input: ["3 + (4 * 5)"], expected: true },
  { name: "digits around invalid brackets", input: ["3 + (4 * 5]"], expected: false },
  { name: "only non-bracket characters", input: ["hello world"], expected: true },
  { name: "whitespace and newlines only", input: ["  \n\t  "], expected: true },
  {
    name: "punctuation around valid nested brackets",
    input: ["note: [item1, item2, {key: value}]!"],
    expected: true,
  },
  {
    name: "punctuation around mismatched brackets",
    input: ["note: [item1, item2, {key: value)!"],
    expected: false,
  },
  { name: "word characters wrapping mismatched types", input: ["foo(bar[baz)qux]"], expected: false },
  { name: "word characters wrapping correct nesting", input: ["foo(bar[baz]qux)"], expected: true },
  { name: "lone unmatched opener among letters", input: ["start(middle end"], expected: false },
  { name: "lone unmatched closer among letters", input: ["start) middle end"], expected: false },
  { name: "unicode and emoji around valid brackets", input: ["✨(😀[🎉]👍)✨"], expected: true },
  { name: "unicode and emoji around invalid brackets", input: ["✨(😀[🎉]👍"], expected: false },
  { name: "mathematical expression valid", input: ["(3 + [4 * (5 - 2)]) / {1}"], expected: true },
  { name: "mathematical expression invalid", input: ["(3 + [4 * (5 - 2)) / {1}]"], expected: false },
];
