name: Run Tests
on: [push] # Triggers tests automatically

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Pulls your code
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm ci
        working-directory: ./typescript # Changes to the frontend folder

      - name: Run tests in subfolder
        run: npm test
        working-directory: ./typescript # Changes to the frontend folder

      - name: Generate Test Badge Data
        uses: github/marketplace/actions/ci-badges@v1 # Adapt to an active marketplace badge action
        with:
          auth: ${{ secrets.CLAYTON_TREDER_GIST }} # Create a personal access token with 'gist' scope
          gistID: gist:af4877d519a5dd3b94cbee51330ed088  
